export const homeContent = {
  dateLabel: "Mon, Aug 3",
  greeting: "Good morning, Mani! 👋",
  whoopSubgreeting: "Let's make it a great day.",
  avatarInitial: "M",
  readyPercent: 72,
  readyHeadline: "Today you're 72% ready",
  energyLabel: "Energy",
  energyValue: "good",
  recoveryLabel: "Recovery",
  recoveryValue: "fair",
  onTrackLabel: "On track",
  dayBadge: "Day 12 of 42",
  continueLabel: "Continue my day →",
  planTitle: "Your plan today",
  viewProgramLabel: "View program →",
  tasks: [
    {
      id: "breakfast",
      number: 1,
      title: "Log breakfast",
      meta: "8:00 AM · Protein-focused",
      icon: "restaurant" as const,
      complete: true,
    },
    {
      id: "walk",
      number: 2,
      title: "Walk + Core A",
      meta: "25 min · Beginner",
      icon: "barbell" as const,
      complete: false,
    },
    {
      id: "checkin",
      number: 3,
      title: "Evening check-in",
      meta: "Weight · reflection",
      icon: "phone-portrait" as const,
      complete: false,
    },
  ],
  leanScore: {
    title: "LEAN SCORE",
    value: 65,
    max: 100,
    rows: [
      { id: "nutrition", label: "Nutrition", value: 78, icon: "nutrition" as const },
      { id: "training", label: "Training", value: 60, icon: "barbell" as const },
      { id: "recovery", label: "Recovery", value: 71, icon: "moon" as const },
      { id: "consistency", label: "Consistency", value: 82, icon: "checkmark-circle" as const },
    ],
    win: "Biggest win today: hydrate + finish your workout",
  },
  thisWeek: {
    title: "THIS WEEK",
    bars: [
      { id: "workouts", label: "Workouts", value: 4, max: 5, tone: "cobalt" as const },
      { id: "meals", label: "Meals", value: 5, max: 7, tone: "green" as const },
      { id: "hydration", label: "Hydration", value: 4, max: 7, tone: "cobalt" as const },
    ],
  },
  mindset: {
    label: "MINDSET TODAY",
    quote: "Don't aim for perfect. Aim for consistent.",
    support: "Small steps. Big change.",
  },
  explorer: {
    heading: "Find your Lean Lab",
    labBody: "Personalized 30-day labs for nutrition, training, and the habits that last.",
    recommendedLabel: "Recommended for you",
    moreLabel: "More Labs",
    seeAll: "See all",
    viewLabs: "View Labs",
    subgreeting: "Let's make it a great day.",
  },
} as const;
